# Generated by Django 5.2 on 2025-04-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created_at"]},
        ),
    ]
